const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const KEY='personal-startpage-v1';
const defaults={name:'',engine:'https://www.google.com/search?q=',theme:'dark',notes:'',tasks:[],events:[],homework:[],goals:[],links:[
{id:'g',title:'Google',url:'https://www.google.com',icon:'G'},
{id:'yt',title:'YouTube',url:'https://www.youtube.com',icon:'▶'},
{id:'gh',title:'GitHub',url:'https://github.com',icon:'◆'},
{id:'ns',title:'NewSky',url:'https://newsky.app',icon:'✈'}
]};
let state=JSON.parse(localStorage.getItem(KEY)||'null')||structuredClone(defaults);
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7);
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(window._toast);window._toast=setTimeout(()=>e.classList.remove('show'),2200)}
function escape(s=''){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function localDate(d=new Date()){return d.toLocaleDateString('nl-NL',{weekday:'long',day:'numeric',month:'long',year:'numeric'})}
function tick(){const d=new Date();$('#clock').textContent=d.toLocaleTimeString('nl-NL');$('#todayText').textContent=localDate(d);const h=d.getHours();$('#greeting').textContent=h<12?'Goedemorgen':h<18?'Goedemiddag':'Goedenavond';if(state.name)$('#greeting').textContent=(h<12?'Goedemorgen, ':h<18?'Goedemiddag, ':'Goedenavond, ')+state.name}
function navigate(view){$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$$('.view').forEach(v=>v.classList.toggle('active',v.id==='view-'+view));const active=$('.nav-item.active');$('#breadcrumb').textContent=active?.textContent.trim()||'Overzicht';$('.sidebar').classList.remove('open');if(view==='agenda')renderAgenda();if(view==='tasks')renderTasks();if(view==='homework')renderHomework();if(view==='goals')renderGoals();if(view==='links')renderLinks()}
$('#nav').addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(b)navigate(b.dataset.view)});
$$('[data-go]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.go)));
$('#menuBtn').onclick=()=>$('.sidebar').classList.toggle('open');
$('#focusBtn').onclick=()=>document.documentElement.requestFullscreen?.().catch(()=>{});
$('#themeBtn').onclick=()=>setTheme(state.theme==='dark'?'light':'dark');
function setTheme(t){state.theme=t;document.body.classList.toggle('light',t==='light');save();$$('[data-theme]').forEach(b=>b.classList.toggle('active',b.dataset.theme===t))}
function render(){tick();setTheme(state.theme);$('#notes').value=state.notes;$('#nameSetting').value=state.name;$('#engine').value=state.engine;$('#engineSetting').value=state.engine;renderHome();renderAgenda();renderTasks();renderHomework();renderGoals();renderLinks()}
function renderHome(){const ev=[...state.events].sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)).slice(0,3);$('#agendaPreview').innerHTML=ev.length?ev.map(e=>'<div class="list-row"><div class="row-main"><strong>'+escape(e.title)+'</strong><small>'+escape(e.date)+(e.time?' · '+escape(e.time):'')+'</small></div></div>').join(''):'<div class="empty">Nog geen afspraken.</div>';const tasks=state.tasks.filter(t=>!t.done).slice(0,4);$('#taskPreview').innerHTML=tasks.length?tasks.map(t=>taskRow(t)).join(''):'<div class="empty">Alles gedaan. Lekker.</div>';$('#quickPreview').innerHTML=state.links.slice(0,4).map(l=>'<a class="quick" href="'+escape(l.url)+'" target="_blank" rel="noopener"><b>'+escape(l.icon||'↗')+'</b>'+escape(l.title)+'</a>').join('')||'<div class="empty">Voeg een link toe.</div>';const goals=state.goals.slice(0,3);$('#goalPreview').innerHTML=goals.length?goals.map(g=>'<div class="goal-card"><strong>'+escape(g.title)+'</strong><div class="progress"><div class="bar" style="width:'+Math.min(100,Math.max(0,g.progress||0))+'%"></div></div><div class="goal-meta"><span>'+Math.round(g.progress||0)+'%</span></div></div>').join(''):'<div class="empty">Nog geen doelen.</div>';const hw=state.homework.filter(x=>!x.done).slice(0,3);$('#homeworkPreview').innerHTML=hw.length?hw.map(x=>'<div class="list-row"><div class="row-main"><strong>'+escape(x.title)+'</strong><small>'+escape(x.subject||'')+(x.due?' · '+escape(x.due):'')+'</small></div></div>').join(''):'<div class="empty">Geen openstaand huiswerk.</div>'}
function taskRow(t){return '<div class="list-row"><button class="check '+(t.done?'done':'')+'" data-task="'+t.id+'">'+(t.done?'✓':'')+'</button><div class="row-main"><strong class="'+(t.done?'strike':'')+'">'+escape(t.title)+'</strong><small>'+escape(t.priority||'Normaal')+'</small></div></div>'}
document.addEventListener('click',e=>{const id=e.target.closest('[data-task]')?.dataset.task;if(id){const t=state.tasks.find(x=>x.id===id);if(t){t.done=!t.done;save();render()}}const del=e.target.closest('[data-delete]')?.dataset.delete;if(del){const [type,key]=del.split(':');if(state[type])state[type]=state[type].filter(x=>x.id!==key);save();render()}});

function renderAgenda(){$('#agendaList').innerHTML=state.events.length?[...state.events].sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)).map(e=>'<div class="item-card"><div class="item-content"><strong>'+escape(e.title)+'</strong><small>'+escape(e.date)+(e.time?' · '+escape(e.time):'')+(e.description?' · '+escape(e.description):'')+'</small></div><div class="item-actions"><button class="small-btn" data-delete="events:'+e.id+'">Verwijder</button></div></div>').join(''):'<div class="empty">Je agenda is nog leeg. Voeg je eerste afspraak toe.</div>'}
let taskFilter='all';
function renderTasks(){let a=state.tasks;if(taskFilter==='open')a=a.filter(x=>!x.done);if(taskFilter==='done')a=a.filter(x=>x.done);$('#tasksList').innerHTML=a.length?a.map(t=>'<div class="item-card"><button class="check '+(t.done?'done':'')+'" data-task="'+t.id+'">'+(t.done?'✓':'')+'</button><div class="item-content"><strong>'+escape(t.title)+'</strong><small>'+escape(t.priority||'Normaal')+(t.due?' · '+escape(t.due):'')+'</small></div><button class="small-btn" data-delete="tasks:'+t.id+'">Verwijder</button></div>').join(''):'<div class="empty">Geen taken in deze weergave.</div>'}
$$('.filter').forEach(b=>b.onclick=()=>{$$('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');taskFilter=b.dataset.filter;renderTasks()});
function renderHomework(){$('#homeworkList').innerHTML=state.homework.length?state.homework.map(x=>'<div class="item-card"><button class="check '+(x.done?'done':'')+'" data-hw="'+x.id+'">'+(x.done?'✓':'')+'</button><div class="item-content"><strong>'+escape(x.title)+'</strong><small>'+escape(x.subject||'Geen vak')+(x.due?' · inleveren '+escape(x.due):'')+'</small></div><button class="small-btn" data-delete="homework:'+x.id+'">Verwijder</button></div>').join(''):'<div class="empty">Nog geen huiswerk toegevoegd.</div>'}
document.addEventListener('click',e=>{const id=e.target.closest('[data-hw]')?.dataset.hw;if(id){const x=state.homework.find(v=>v.id===id);if(x){x.done=!x.done;save();render()}}});
function renderGoals(){$('#goalsList').innerHTML=state.goals.length?state.goals.map(g=>'<div class="card goal-card"><strong>'+escape(g.title)+'</strong><div class="progress"><div class="bar" style="width:'+Math.min(100,Math.max(0,g.progress||0))+'%"></div></div><div class="goal-meta"><span>'+Math.round(g.progress||0)+'% voltooid</span><button class="small-btn" data-delete="goals:'+g.id+'">Verwijder</button></div></div>').join(''):'<div class="empty">Nog geen doelen. Zet iets kleins op papier en begin.</div>'}
function renderLinks(){$('#linksList').innerHTML=state.links.length?state.links.map(l=>'<div class="card link-card"><div class="link-symbol">'+escape(l.icon||'↗')+'</div><div><strong>'+escape(l.title)+'</strong><small>'+escape(l.url)+'</small></div><a class="small-btn" href="'+escape(l.url)+'" target="_blank" rel="noopener">Open</a><button class="small-btn" data-delete="links:'+l.id+'">×</button></div>').join(''):'<div class="empty">Nog geen links.</div>'}

function openModal(type){const titles={task:'Taak toevoegen',event:'Afspraak toevoegen',homework:'Huiswerk toevoegen',goal:'Doel toevoegen',link:'Link toevoegen'};$('#modalTitle').textContent=titles[type];let fields='';if(type==='task')fields='<label>Taak<input name="title" required autofocus></label><label>Prioriteit<select name="priority"><option>Normaal</option><option>Hoog</option><option>Laag</option></select></label><label>Datum<input type="date" name="due"></label>';if(type==='event')fields='<label>Naam<input name="title" required autofocus></label><label>Datum<input type="date" name="date" required></label><label>Tijd<input type="time" name="time"></label><label>Beschrijving<textarea name="description"></textarea></label>';if(type==='homework')fields='<label>Opdracht<input name="title" required autofocus></label><label>Vak<input name="subject"></label><label>Inleverdatum<input type="date" name="due"></label>';if(type==='goal')fields='<label>Doel<input name="title" required autofocus></label><label>Voortgang (%)<input type="number" name="progress" min="0" max="100" value="0"></label>';if(type==='link')fields='<label>Naam<input name="title" required autofocus></label><label>URL<input type="url" name="url" placeholder="https://..." required></label><label>Icoon / letter<input name="icon" value="↗"></label>';$('#modalForm').innerHTML='<div class="form-grid">'+fields+'<button class="primary form-submit">Opslaan</button></div>';$('#modal').classList.add('open');$('#modalForm').querySelector('input')?.focus();$('#modalForm').onsubmit=e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));f.id=uid();if(type==='task')state.tasks.push({...f,done:false});if(type==='event')state.events.push(f);if(type==='homework')state.homework.push({...f,done:false});if(type==='goal')state.goals.push({...f,progress:Number(f.progress)||0});if(type==='link')state.links.push(f);save();$('#modal').classList.remove('open');render();toast('Opgeslagen')}}
$$('[data-add]').forEach(b=>b.addEventListener('click',()=>openModal(b.dataset.add)));
$('#modalClose').onclick=()=>$('#modal').classList.remove('open');$('#modal').addEventListener('click',e=>{if(e.target.id==='modal')$('#modal').classList.remove('open')});
$('#searchBtn').onclick=doSearch;$('#search').addEventListener('keydown',e=>{if(e.key==='Enter')doSearch()});function doSearch(){const q=$('#search').value.trim();if(q)location.href=state.engine+encodeURIComponent(q)}
$('#notes').addEventListener('input',e=>{state.notes=e.target.value;save();$('#noteState').textContent='Opgeslagen ✓';clearTimeout(window._note);window._note=setTimeout(()=>$('#noteState').textContent='Automatisch opgeslagen',1000)});
$('#nameSetting').addEventListener('input',e=>{state.name=e.target.value;save();tick()});$('#engineSetting').onchange=e=>{state.engine=e.target.value;$('#engine').value=e.target.value;save()};$('#engine').onchange=e=>{state.engine=e.target.value;$('#engineSetting').value=e.target.value;save()};$$('[data-theme]').forEach(b=>b.onclick=()=>setTheme(b.dataset.theme));
$('#resetBtn').onclick=()=>{if(confirm('Weet je zeker dat je alle lokale gegevens wilt wissen?')){localStorage.removeItem(KEY);location.reload()}};
async function weather(){try{const pos=await new Promise((res,rej)=>navigator.geolocation.getCurrentPosition(res,rej,{timeout:7000}));const {latitude,longitude}=pos.coords;const r=await fetch('https://api.open-meteo.com/v1/forecast?latitude='+latitude+'&longitude='+longitude+'&current=temperature_2m,weather_code,wind_speed_10m&timezone=auto');const d=await r.json();const code=d.current.weather_code;const map=code<=3?['☀','Helder / bewolkt']:code<=48?['☁','Mist / bewolking']:code<=67?['🌧','Regen']:code<=77?['❄','Sneeuw']:code<=82?['🌦','Buien']:['⛈','Onweer'];$('#weatherIcon').textContent=map[0];$('#weatherText').textContent=map[1];$('#temperature').textContent=Math.round(d.current.temperature_2m)+'°';$('#weatherExtra').textContent='Wind '+Math.round(d.current.wind_speed_10m)+' km/u';$('#weatherPlace').textContent='Huidige locatie'}catch(e){$('#weatherText').textContent='Locatie niet beschikbaar';$('#weatherExtra').textContent='Sta locatie toe voor live weer'}}weather();setInterval(tick,1000);render();